name: app_features
description: Feature、跨 Feature API、Controller、页面与路由包边界
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  app_core: any
  app_data: any
  app_im: any
  app_media: any
  app_media_capture_bridge: any
  app_ui: any
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get:
    git:
      url: https://github.com/bladeofgod/getx.git
      ref: 7bfcd9c3711c8880ee730579724dabe54f4e2598
  go_router: ^15.1.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/auth/
    - assets/images/cart/
    - assets/images/catalog/
    - assets/images/catalog/categories/
    - assets/images/catalog/products/
    - assets/images/profile/
    - assets/images/wishlist/
    - assets/images/welcome/shoppe_brand.png
