// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generator: media_capture_wire/1
// Source: docs/bridge/contracts/media-capture.wire.json
// Source digest (SHA-256): 76e65a567971ca209e0b4f50412e79002a83eda04869149f21d136a7c6569d27
package com.example.media_capture

internal const val generatedMediaCaptureWireVersion: Int = 3
internal const val generatedCommandsChannel: String = "com.example.media_capture.commands"
internal const val generatedEventsChannel: String = "com.example.media_capture.events"

internal enum class GeneratedMediaCaptureWireMethod(val wireValue: String) {
    cancel("cancel"),
    confirm("confirm"),
    dismissCaptureFlow("dismiss_capture_flow"),
    materializeMediaResource("materialize_media_resource"),
    presentCaptureFlow("present_capture_flow"),
    readMediaThumbnail("read_media_thumbnail"),
    releaseMaterializedMedia("release_materialized_media"),
    releaseMedia("release_media"),
    retake("retake"),
    setFlashMode("set_flash_mode"),
    setFocusPoint("set_focus_point"),
    setZoom("set_zoom"),
    startRecording("start_recording"),
    startSession("start_session"),
    stopRecording("stop_recording"),
    switchCamera("switch_camera"),
    takePhoto("take_photo");
}

internal enum class GeneratedMediaCaptureWireEvent(val wireValue: String) {
    mediaLeaseExpired("media_lease_expired"),
    mediaPreviewReady("media_preview_ready"),
    mediaReadRevoked("media_read_revoked"),
    sessionFailed("session_failed"),
    sessionReady("session_ready");
}

internal enum class GeneratedMediaCaptureWireResult(val wireValue: String) {
    captureFlowCancelled("capture_flow_cancelled"),
    captureFlowConfirmed("capture_flow_confirmed"),
    captureFlowDismissed("capture_flow_dismissed"),
    confirmedMedia("confirmed_media"),
    controlApplied("control_applied"),
    materializedMediaReleased("materialized_media_released"),
    materializedMediaResource("materialized_media_resource"),
    mediaPreview("media_preview"),
    mediaReleased("media_released"),
    mediaThumbnail("media_thumbnail"),
    recordingStarted("recording_started"),
    retakeReady("retake_ready"),
    sessionCancelled("session_cancelled"),
    sessionCreated("session_created");
}

internal enum class GeneratedMediaCaptureWireFailure(val wireValue: String) {
    sessionTimeout("session_timeout");
}

internal enum class GeneratedMediaCaptureWireError(val wireValue: String) {
    bridgeOverloaded("bridge_overloaded"),
    bridgeUnavailable("bridge_unavailable"),
    duplicateRequest("duplicate_request"),
    encodingFailed("encoding_failed"),
    incompatibleWireVersion("incompatible_wire_version"),
    invalidArgument("invalid_argument"),
    invalidState("invalid_state"),
    invalidWirePayload("invalid_wire_payload"),
    listenerAlreadyActive("listener_already_active"),
    materializedMediaInvalid("materialized_media_invalid"),
    mediaExportCancelled("media_export_cancelled"),
    mediaExportConflict("media_export_conflict"),
    mediaExportOverloaded("media_export_overloaded"),
    mediaExportReadFailed("media_export_read_failed"),
    mediaExportSinkRejected("media_export_sink_rejected"),
    mediaExportTimedOut("media_export_timed_out"),
    mediaExportTooLarge("media_export_too_large"),
    mediaExportWriteFailed("media_export_write_failed"),
    mediaInvalid("media_invalid"),
    permissionDenied("permission_denied"),
    permissionPermanentlyDenied("permission_permanently_denied"),
    permissionRestricted("permission_restricted"),
    presentationConflict("presentation_conflict"),
    resourceInUse("resource_in_use"),
    sessionConflict("session_conflict"),
    sessionInvalid("session_invalid"),
    sessionTimeout("session_timeout"),
    storageFull("storage_full"),
    systemInterrupted("system_interrupted"),
    thumbnailGenerationCancelled("thumbnail_generation_cancelled"),
    thumbnailGenerationFailed("thumbnail_generation_failed"),
    thumbnailOverloaded("thumbnail_overloaded"),
    transferStoreOverloaded("transfer_store_overloaded"),
    transferStoreUnavailable("transfer_store_unavailable"),
    unsupportedCapability("unsupported_capability"),
    wireEncodingFailed("wire_encoding_failed");
}

internal data class GeneratedWireFieldDescriptor(
    val id: String,
    val key: String,
    val type: String,
    val required: Boolean,
    val nullable: Boolean,
    val enumValues: Set<String>,
    val minimum: String?,
    val maximum: String?,
    val allowedIntegers: Set<Long>,
    val minItems: Int?,
    val maxItems: Int?,
    val finite: Boolean,
    val format: String,
    val boundarySource: String?,
    val outOfRangePolicy: String,
)

internal val generatedMediaCaptureWireFields: List<GeneratedWireFieldDescriptor> = listOf(
    GeneratedWireFieldDescriptor(
        id = "active_camera",
        key = "activeCamera",
        type = "string",
        required = true, nullable = false,
        enumValues = setOf("rear", "front"),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "none",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "audio_enabled",
        key = "audioEnabled",
        type = "bool",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "none",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "audio_included",
        key = "audioIncluded",
        type = "bool",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "none",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "available_cameras",
        key = "availableCameras",
        type = "list_string",
        required = true, nullable = false,
        enumValues = setOf("rear", "front"),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = 1,
        maxItems = 2,
        finite = false,
        format = "none",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "byte_length",
        key = "byteLength",
        type = "int",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "1",
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "byte_length",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "content_type",
        key = "contentType",
        type = "string",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "mime_type",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "duration_millis",
        key = "durationMillis",
        type = "int",
        required = true, nullable = true,
        enumValues = emptySet(),
        minimum = "1",
        maximum = "60000",
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "duration_millis",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "enabled_media_types",
        key = "enabledMediaTypes",
        type = "list_string",
        required = true, nullable = false,
        enumValues = setOf("photo", "video"),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = 1,
        maxItems = 2,
        finite = false,
        format = "none",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "expires_at",
        key = "expiresAt",
        type = "int",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "0",
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "unix_epoch_millis",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "export_handle",
        key = "exportHandle",
        type = "string",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "opaque_handle",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "file_uri",
        key = "fileUri",
        type = "string",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "canonical_file_uri",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "flash_mode",
        key = "flashMode",
        type = "string",
        required = true, nullable = false,
        enumValues = setOf("off", "on", "auto", "torch"),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "none",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "focus_point_supported",
        key = "focusPointSupported",
        type = "bool",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "none",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "integrity_sha256",
        key = "integritySha256",
        type = "string",
        required = false, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "lowercase_sha256_hex",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "lease_expires_at",
        key = "leaseExpiresAt",
        type = "int",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "0",
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "unix_epoch_millis",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "max_pixel_edge",
        key = "maxPixelEdge",
        type = "int",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "64",
        maximum = "512",
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "pixel_dimension",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "max_video_duration_millis",
        key = "maxVideoDurationMillis",
        type = "int",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "1",
        maximum = "60000",
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "duration_millis",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "max_zoom_factor",
        key = "maxZoomFactor",
        type = "double",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "0.01",
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "zoom_bound",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "media_handle",
        key = "mediaHandle",
        type = "string",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "opaque_handle",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "media_type",
        key = "mediaType",
        type = "string",
        required = true, nullable = false,
        enumValues = setOf("photo", "video"),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "none",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "min_zoom_factor",
        key = "minZoomFactor",
        type = "double",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "0.01",
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "zoom_bound",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "normalized_x",
        key = "normalizedX",
        type = "double",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "0",
        maximum = "1",
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "normalized_coordinate",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "normalized_y",
        key = "normalizedY",
        type = "double",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "0",
        maximum = "1",
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "normalized_coordinate",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "orientation_degrees",
        key = "orientationDegrees",
        type = "int",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = setOf(0L, 90L, 180L, 270L),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "orientation_degrees",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "pixel_height",
        key = "pixelHeight",
        type = "int",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "1",
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "pixel_dimension",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "pixel_width",
        key = "pixelWidth",
        type = "int",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "1",
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "pixel_dimension",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "poster_frame_millis",
        key = "posterFrameMillis",
        type = "int",
        required = true, nullable = true,
        enumValues = emptySet(),
        minimum = "0",
        maximum = "60000",
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "duration_millis",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "preferred_camera",
        key = "preferredCamera",
        type = "string",
        required = true, nullable = false,
        enumValues = setOf("rear", "front"),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "none",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "presentation_request_id",
        key = "presentationRequestId",
        type = "string",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "opaque_request_id",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "session_handle",
        key = "sessionHandle",
        type = "string",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "opaque_handle",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "supported_flash_modes",
        key = "supportedFlashModes",
        type = "list_string",
        required = true, nullable = false,
        enumValues = setOf("off", "on", "auto", "torch"),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = 1,
        maxItems = 4,
        finite = false,
        format = "none",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "switch_camera_supported",
        key = "switchCameraSupported",
        type = "bool",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "none",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "terminal_failure_id",
        key = "terminalFailureId",
        type = "string",
        required = true, nullable = false,
        enumValues = setOf("permission_denied", "permission_restricted", "permission_permanently_denied", "resource_in_use", "storage_full", "encoding_failed", "system_interrupted", "session_timeout"),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "none",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "thumbnail_byte_length",
        key = "thumbnailByteLength",
        type = "int",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "1",
        maximum = "524288",
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "byte_length",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "thumbnail_content_type",
        key = "thumbnailContentType",
        type = "string",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "image_jpeg_content_type",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "thumbnail_copy",
        key = "thumbnailCopy",
        type = "bytes",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = false,
        format = "caller_owned_bounded_copy",
        boundarySource = null,
        outOfRangePolicy = "not_applicable",
    ),
    GeneratedWireFieldDescriptor(
        id = "thumbnail_orientation_degrees",
        key = "thumbnailOrientationDegrees",
        type = "int",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = setOf(0L),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "orientation_degrees",
        boundarySource = null,
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "thumbnail_pixel_height",
        key = "thumbnailPixelHeight",
        type = "int",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "1",
        maximum = "512",
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "pixel_dimension",
        boundarySource = "max_pixel_edge",
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "thumbnail_pixel_width",
        key = "thumbnailPixelWidth",
        type = "int",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = "1",
        maximum = "512",
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "pixel_dimension",
        boundarySource = "max_pixel_edge",
        outOfRangePolicy = "reject",
    ),
    GeneratedWireFieldDescriptor(
        id = "zoom_factor",
        key = "zoomFactor",
        type = "double",
        required = true, nullable = false,
        enumValues = emptySet(),
        minimum = null,
        maximum = null,
        allowedIntegers = emptySet(),
        minItems = null,
        maxItems = null,
        finite = true,
        format = "zoom_factor",
        boundarySource = "session_zoom_range",
        outOfRangePolicy = "reject",
    ),
)

internal val generatedPayloadFieldIds: Map<String, Set<String>> = mapOf(
    "capture_flow_dismissed_result_payload" to emptySet(),
    "confirmed_media_result_payload" to setOf("media_handle", "media_type", "pixel_width", "pixel_height", "duration_millis", "orientation_degrees", "byte_length", "lease_expires_at"),
    "control_applied_result_payload" to setOf("session_handle"),
    "dismiss_capture_flow_request_payload" to setOf("presentation_request_id"),
    "flash_mode_request_payload" to setOf("session_handle", "flash_mode"),
    "focus_point_request_payload" to setOf("session_handle", "normalized_x", "normalized_y"),
    "materialize_media_resource_request_payload" to setOf("media_handle"),
    "materialized_media_released_result_payload" to emptySet(),
    "materialized_media_result_payload" to setOf("export_handle", "file_uri", "media_type", "content_type", "byte_length", "duration_millis", "expires_at", "integrity_sha256"),
    "media_handle_request_payload" to setOf("media_handle"),
    "media_lease_expired_event_payload" to setOf("media_handle"),
    "media_preview_ready_event_payload" to setOf("session_handle", "media_handle", "media_type", "pixel_width", "pixel_height", "duration_millis", "orientation_degrees", "byte_length"),
    "media_preview_result_payload" to setOf("media_handle", "media_type", "pixel_width", "pixel_height", "duration_millis", "orientation_degrees", "byte_length"),
    "media_read_revoked_event_payload" to setOf("media_handle"),
    "media_released_result_payload" to setOf("media_handle"),
    "media_thumbnail_request_payload" to setOf("media_handle", "max_pixel_edge"),
    "media_thumbnail_result_payload" to setOf("media_handle", "thumbnail_copy", "thumbnail_byte_length", "thumbnail_pixel_width", "thumbnail_pixel_height", "thumbnail_content_type", "thumbnail_orientation_degrees", "media_type", "poster_frame_millis"),
    "recording_started_result_payload" to setOf("session_handle", "audio_included"),
    "release_materialized_media_request_payload" to setOf("export_handle"),
    "retake_ready_result_payload" to setOf("session_handle"),
    "session_action_request_payload" to setOf("session_handle"),
    "session_cancelled_result_payload" to setOf("session_handle"),
    "session_created_result_payload" to setOf("session_handle"),
    "session_failed_event_payload" to setOf("session_handle", "terminal_failure_id"),
    "session_ready_event_payload" to setOf("session_handle", "active_camera", "available_cameras", "switch_camera_supported", "supported_flash_modes", "focus_point_supported", "min_zoom_factor", "max_zoom_factor"),
    "session_timeout_failure_payload" to setOf("session_handle"),
    "start_session_request_payload" to setOf("enabled_media_types", "preferred_camera", "audio_enabled", "max_video_duration_millis"),
    "zoom_request_payload" to setOf("session_handle", "zoom_factor"),
)

internal data class GeneratedWirePayloadDescriptor(
    val id: String, val kind: String,
    val fieldIds: Set<String>, val unknownFieldPolicy: String,
)
internal val generatedPayloadDescriptors = listOf(
    GeneratedWirePayloadDescriptor("capture_flow_dismissed_result_payload", "result", emptySet(), "reject"),
    GeneratedWirePayloadDescriptor("confirmed_media_result_payload", "result", setOf("media_handle", "media_type", "pixel_width", "pixel_height", "duration_millis", "orientation_degrees", "byte_length", "lease_expires_at"), "reject"),
    GeneratedWirePayloadDescriptor("control_applied_result_payload", "result", setOf("session_handle"), "reject"),
    GeneratedWirePayloadDescriptor("dismiss_capture_flow_request_payload", "request", setOf("presentation_request_id"), "reject"),
    GeneratedWirePayloadDescriptor("flash_mode_request_payload", "request", setOf("session_handle", "flash_mode"), "reject"),
    GeneratedWirePayloadDescriptor("focus_point_request_payload", "request", setOf("session_handle", "normalized_x", "normalized_y"), "reject"),
    GeneratedWirePayloadDescriptor("materialize_media_resource_request_payload", "request", setOf("media_handle"), "reject"),
    GeneratedWirePayloadDescriptor("materialized_media_released_result_payload", "result", emptySet(), "reject"),
    GeneratedWirePayloadDescriptor("materialized_media_result_payload", "result", setOf("export_handle", "file_uri", "media_type", "content_type", "byte_length", "duration_millis", "expires_at", "integrity_sha256"), "reject"),
    GeneratedWirePayloadDescriptor("media_handle_request_payload", "request", setOf("media_handle"), "reject"),
    GeneratedWirePayloadDescriptor("media_lease_expired_event_payload", "event", setOf("media_handle"), "reject"),
    GeneratedWirePayloadDescriptor("media_preview_ready_event_payload", "event", setOf("session_handle", "media_handle", "media_type", "pixel_width", "pixel_height", "duration_millis", "orientation_degrees", "byte_length"), "reject"),
    GeneratedWirePayloadDescriptor("media_preview_result_payload", "result", setOf("media_handle", "media_type", "pixel_width", "pixel_height", "duration_millis", "orientation_degrees", "byte_length"), "reject"),
    GeneratedWirePayloadDescriptor("media_read_revoked_event_payload", "event", setOf("media_handle"), "reject"),
    GeneratedWirePayloadDescriptor("media_released_result_payload", "result", setOf("media_handle"), "reject"),
    GeneratedWirePayloadDescriptor("media_thumbnail_request_payload", "request", setOf("media_handle", "max_pixel_edge"), "reject"),
    GeneratedWirePayloadDescriptor("media_thumbnail_result_payload", "result", setOf("media_handle", "thumbnail_copy", "thumbnail_byte_length", "thumbnail_pixel_width", "thumbnail_pixel_height", "thumbnail_content_type", "thumbnail_orientation_degrees", "media_type", "poster_frame_millis"), "reject"),
    GeneratedWirePayloadDescriptor("recording_started_result_payload", "result", setOf("session_handle", "audio_included"), "reject"),
    GeneratedWirePayloadDescriptor("release_materialized_media_request_payload", "request", setOf("export_handle"), "reject"),
    GeneratedWirePayloadDescriptor("retake_ready_result_payload", "result", setOf("session_handle"), "reject"),
    GeneratedWirePayloadDescriptor("session_action_request_payload", "request", setOf("session_handle"), "reject"),
    GeneratedWirePayloadDescriptor("session_cancelled_result_payload", "result", setOf("session_handle"), "reject"),
    GeneratedWirePayloadDescriptor("session_created_result_payload", "result", setOf("session_handle"), "reject"),
    GeneratedWirePayloadDescriptor("session_failed_event_payload", "event", setOf("session_handle", "terminal_failure_id"), "reject"),
    GeneratedWirePayloadDescriptor("session_ready_event_payload", "event", setOf("session_handle", "active_camera", "available_cameras", "switch_camera_supported", "supported_flash_modes", "focus_point_supported", "min_zoom_factor", "max_zoom_factor"), "reject"),
    GeneratedWirePayloadDescriptor("session_timeout_failure_payload", "failure", setOf("session_handle"), "reject"),
    GeneratedWirePayloadDescriptor("start_session_request_payload", "request", setOf("enabled_media_types", "preferred_camera", "audio_enabled", "max_video_duration_millis"), "reject"),
    GeneratedWirePayloadDescriptor("zoom_request_payload", "request", setOf("session_handle", "zoom_factor"), "reject"),
)
internal data class GeneratedWireErrorDescriptor(
    val code: String, val source: String,
    val capabilityFailureId: String?,
    val recoverable: Boolean, val terminal: Boolean,
    val messagePolicy: String, val detailsAllowedKeys: Set<String>,
)
internal val generatedErrorDescriptors = listOf(
    GeneratedWireErrorDescriptor("bridge_overloaded", "wire_protocol", null, true, false, "static_redacted", setOf("operation", "capacity")),
    GeneratedWireErrorDescriptor("bridge_unavailable", "wire_protocol", null, true, false, "static_redacted", setOf("operation", "lifecycleReason")),
    GeneratedWireErrorDescriptor("duplicate_request", "wire_protocol", null, true, false, "static_redacted", setOf("operation")),
    GeneratedWireErrorDescriptor("encoding_failed", "capability_failure", "encoding_failed", true, true, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("incompatible_wire_version", "wire_protocol", null, false, false, "static_redacted", setOf("actualWireVersion", "expectedWireVersion")),
    GeneratedWireErrorDescriptor("invalid_argument", "capability_failure", "invalid_argument", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("invalid_state", "capability_failure", "invalid_state", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("invalid_wire_payload", "wire_protocol", null, true, false, "static_redacted", setOf("operation", "field", "reason")),
    GeneratedWireErrorDescriptor("listener_already_active", "wire_protocol", null, true, false, "static_redacted", emptySet()),
    GeneratedWireErrorDescriptor("materialized_media_invalid", "wire_protocol", null, true, false, "static_redacted", setOf("operation")),
    GeneratedWireErrorDescriptor("media_export_cancelled", "capability_failure", "media_export_cancelled", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("media_export_conflict", "capability_failure", "media_export_conflict", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("media_export_overloaded", "capability_failure", "media_export_overloaded", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("media_export_read_failed", "capability_failure", "media_export_read_failed", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("media_export_sink_rejected", "capability_failure", "media_export_sink_rejected", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("media_export_timed_out", "capability_failure", "media_export_timed_out", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("media_export_too_large", "capability_failure", "media_export_too_large", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("media_export_write_failed", "capability_failure", "media_export_write_failed", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("media_invalid", "capability_failure", "media_invalid", false, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("permission_denied", "capability_failure", "permission_denied", true, true, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("permission_permanently_denied", "capability_failure", "permission_permanently_denied", false, true, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("permission_restricted", "capability_failure", "permission_restricted", false, true, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("presentation_conflict", "wire_protocol", null, true, false, "static_redacted", setOf("operation", "capacity")),
    GeneratedWireErrorDescriptor("resource_in_use", "capability_failure", "resource_in_use", true, true, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("session_conflict", "capability_failure", "session_conflict", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("session_invalid", "capability_failure", "session_invalid", false, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("session_timeout", "capability_failure", "session_timeout", true, true, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("storage_full", "capability_failure", "storage_full", true, true, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("system_interrupted", "capability_failure", "system_interrupted", true, true, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("thumbnail_generation_cancelled", "capability_failure", "thumbnail_generation_cancelled", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("thumbnail_generation_failed", "capability_failure", "thumbnail_generation_failed", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("thumbnail_overloaded", "capability_failure", "thumbnail_overloaded", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("transfer_store_overloaded", "wire_protocol", null, true, false, "static_redacted", setOf("operation", "capacity")),
    GeneratedWireErrorDescriptor("transfer_store_unavailable", "wire_protocol", null, true, false, "static_redacted", setOf("operation", "lifecycleReason")),
    GeneratedWireErrorDescriptor("unsupported_capability", "capability_failure", "unsupported_capability", true, false, "static_redacted", setOf("operation", "capabilityFailureId")),
    GeneratedWireErrorDescriptor("wire_encoding_failed", "wire_protocol", null, false, false, "static_redacted", setOf("operation", "field", "reason")),
)
internal data class GeneratedWireErrorDetailDescriptor(
    val key: String, val type: String, val source: String,
    val enumValues: Set<String>,
    val minLength: Int?, val maxLength: Int?,
    val minimum: String?, val maximum: String?,
    val redaction: String,
)
internal val generatedErrorDetailDescriptors = listOf(
    GeneratedWireErrorDetailDescriptor("actualWireVersion", "int", "request_wire_version", emptySet(), null, null, "-9223372036854775808", "9223372036854775807", "allowlisted_value_only"),
    GeneratedWireErrorDetailDescriptor("capabilityFailureId", "string", "capability_failure_id", setOf("permission_denied", "permission_restricted", "permission_permanently_denied", "resource_in_use", "storage_full", "encoding_failed", "media_invalid", "session_invalid", "unsupported_capability", "system_interrupted", "session_conflict", "invalid_state", "invalid_argument", "session_timeout", "thumbnail_generation_failed", "thumbnail_generation_cancelled", "thumbnail_overloaded", "attachment_generation_retired", "attachment_target_conflict", "media_export_conflict", "media_export_overloaded", "media_export_too_large", "media_export_sink_rejected", "media_export_read_failed", "media_export_write_failed", "media_export_cancelled", "media_export_timed_out"), 1, 64, null, null, "allowlisted_value_only"),
    GeneratedWireErrorDetailDescriptor("capacity", "string", "closed_capacity_code", setOf("active_export_bytes", "active_exports", "active_presentation", "completed_request_tombstones", "pending_requests", "release_tombstones"), 1, 64, null, null, "allowlisted_value_only"),
    GeneratedWireErrorDetailDescriptor("expectedWireVersion", "int", "contract_wire_version", emptySet(), null, null, "-9223372036854775808", "9223372036854775807", "allowlisted_value_only"),
    GeneratedWireErrorDetailDescriptor("field", "string", "declared_field_key_or_unknown", setOf("wireVersion", "requestId", "payload", "resultType", "eventType", "failureType", "enabledMediaTypes", "preferredCamera", "audioEnabled", "maxVideoDurationMillis", "sessionHandle", "flashMode", "normalizedX", "normalizedY", "zoomFactor", "mediaHandle", "activeCamera", "availableCameras", "switchCameraSupported", "supportedFlashModes", "focusPointSupported", "minZoomFactor", "maxZoomFactor", "audioIncluded", "mediaType", "pixelWidth", "pixelHeight", "durationMillis", "orientationDegrees", "byteLength", "leaseExpiresAt", "terminalFailureId", "maxPixelEdge", "thumbnailCopy", "thumbnailByteLength", "thumbnailPixelWidth", "thumbnailPixelHeight", "thumbnailContentType", "thumbnailOrientationDegrees", "posterFrameMillis", "unknown_field", "contentType", "exportHandle", "fileUri", "expiresAt", "integritySha256", "presentationRequestId"), 1, 64, null, null, "allowlisted_value_only"),
    GeneratedWireErrorDetailDescriptor("lifecycleReason", "string", "closed_lifecycle_reason", setOf("engine_detached", "activity_destroyed", "view_controller_destroyed", "adapter_disposed"), 1, 64, null, null, "allowlisted_value_only"),
    GeneratedWireErrorDetailDescriptor("operation", "string", "method_id_or_unknown", setOf("start_session", "take_photo", "start_recording", "stop_recording", "switch_camera", "set_flash_mode", "set_focus_point", "set_zoom", "retake", "confirm", "cancel", "release_media", "read_media_thumbnail", "present_capture_flow", "unknown_operation", "materialize_media_resource", "release_materialized_media", "dismiss_capture_flow"), 1, 64, null, null, "allowlisted_value_only"),
    GeneratedWireErrorDetailDescriptor("reason", "string", "closed_reason_code", setOf("missing_required_field", "unknown_field", "type_mismatch", "null_not_allowed", "non_finite", "out_of_range", "invalid_enum", "invalid_format", "integer_overflow", "result_type_mismatch", "native_value_unencodable"), 1, 64, null, null, "allowlisted_value_only"),
)
internal const val generatedRequestIdWireType: String = "string"
internal const val generatedRequestIdPattern: String = "^[A-Za-z0-9_-]{1,128}\$"
internal const val generatedRequestIdFormat: String = "ascii_token"
internal const val generatedRequestIdMinLength: Int = 1
internal const val generatedRequestIdMaxLength: Int = 128
internal val generatedEnvelopeRequiredKeys: Map<String, Set<String>> = mapOf(
    "/lifecycle/eventEnvelope" to setOf("wireVersion", "eventType", "payload"),
    "/lifecycle/eventListenEnvelope" to setOf("wireVersion"),
    "/lifecycle/failureEnvelope" to setOf("wireVersion", "failureType", "payload"),
    "/lifecycle/requestEnvelope" to setOf("wireVersion", "requestId", "payload"),
    "/lifecycle/resultEnvelope" to setOf("wireVersion", "requestId", "resultType", "payload"),
)
internal val generatedEnvelopeUnknownFieldPolicies: Map<String, String> = mapOf(
    "/lifecycle/eventEnvelope" to "reject",
    "/lifecycle/eventListenEnvelope" to "reject",
    "/lifecycle/failureEnvelope" to "reject",
    "/lifecycle/requestEnvelope" to "reject",
    "/lifecycle/resultEnvelope" to "reject",
)
internal const val generatedSignedIntegerMinimum: Long = Long.MIN_VALUE
internal const val generatedSignedIntegerMaximum: Long = Long.MAX_VALUE
internal val generatedOpaqueHandleLengths: Map<String, IntRange> = mapOf(
    "export_handle" to 22..64,
    "media_handle" to 1..128,
    "session_handle" to 1..128,
)

internal fun generatedHasExactWireKeys(
    value: Map<*, *>, requiredKeys: Set<String>,
): Boolean = value.size == requiredKeys.size && value.keys.all { it in requiredKeys }

internal fun generatedMatchesWireFieldPrimitive(
    value: Any?, field: GeneratedWireFieldDescriptor,
): Boolean {
    if (value == null) return field.nullable
    val validType = when (field.type) {
        "bool" -> value is Boolean
        "bytes" -> value is ByteArray
        "double" -> value is Double
        "int" -> value is Int || value is Long
        "string" -> value is String
        "list_bool" -> value is List<*> && value.all { it is Boolean }
        "list_double" -> value is List<*> && value.all { it is Double }
        "list_int" -> value is List<*> && value.all { it is Int || it is Long }
        "list_string" -> value is List<*> && value.all { it is String }
        else -> false
    }
    if (!validType) return false
    if (value is Double && field.finite && !value.isFinite()) return false
    if (value is Double) {
        if (field.minimum?.toDoubleOrNull()?.let { value < it } == true) return false
        if (field.maximum?.toDoubleOrNull()?.let { value > it } == true) return false
    }
    val integer = when (value) {
        is Int -> value.toLong()
        is Long -> value
        else -> null
    }
    if (integer != null) {
        if (field.minimum?.toLongOrNull()?.let { integer < it } == true) return false
        if (field.maximum?.toLongOrNull()?.let { integer > it } == true) return false
    }
    if (value is Long && field.allowedIntegers.isNotEmpty() && value !in field.allowedIntegers) return false
    if (value is Int && field.allowedIntegers.isNotEmpty() && value.toLong() !in field.allowedIntegers) return false
    val collectionSize = when (value) {
        is ByteArray -> value.size
        is Collection<*> -> value.size
        else -> null
    }
    if (collectionSize != null && field.minItems != null && collectionSize < field.minItems) return false
    if (collectionSize != null && field.maxItems != null && collectionSize > field.maxItems) return false
    if (value is String && field.enumValues.isNotEmpty() && value !in field.enumValues) return false
    if (value is List<*> && field.type == "list_string" && field.enumValues.isNotEmpty() && !value.all { it is String && it in field.enumValues }) return false
    if (value is List<*> && field.type == "list_string" && field.enumValues.isNotEmpty() && value.toSet().size != value.size) return false
    if (value is List<*> && field.type == "list_double" && field.finite && value.any { it is Double && !it.isFinite() }) return false
    return true
}
