name: demo_app
description: Flutter AI Harness Demo 壳工程
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  app_core: any
  app_data: any
  app_features: any
  app_im: any
  app_rtc: any
  app_ui: any
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  marionette_flutter: 0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
