import 'dart:convert';
import 'dart:io';

import 'package:yaml/yaml.dart';

const _generatedMarker =
    'Generated by app/tool/sync_codex_adapters.dart. DO NOT EDIT.';

class CodexAdapterManager {
  CodexAdapterManager(this.root);

  final Directory root;

  List<String> check() {
    try {
      return _check();
    } on FileSystemException catch (error) {
      return ['Codex 适配检查失败：${_fileSystemError(error)}'];
    }
  }

  List<String> _check() {
    final result = _buildExpectedFiles();
    if (result.errors.isNotEmpty) {
      return result.errors;
    }

    final errors = <String>[];
    _validateExpectedSyntax(result.files, errors);
    _validateManagedLayout(result.files.keys, errors);
    if (errors.isNotEmpty) {
      return errors;
    }
    for (final entry in result.files.entries) {
      final file = _file(entry.key);
      if (!file.existsSync()) {
        errors.add('缺少 Codex 适配：${entry.key}');
        continue;
      }
      final actual = file.readAsStringSync();
      if (_normalizeLineEndings(actual) == _normalizeLineEndings(entry.value)) {
        continue;
      }
      if (!_isGenerated(actual)) {
        errors.add('Codex 适配路径存在同名非生成文件：${entry.key}');
      } else {
        errors.add('Codex 适配内容已漂移：${entry.key}');
      }
    }

    for (final file in _generatedAdapterFiles(errors)) {
      final relative = _relative(file);
      if (!result.files.containsKey(relative)) {
        errors.add('存在过期 Codex 适配：$relative');
      }
    }
    return errors;
  }

  void _validateExpectedSyntax(Map<String, String> files, List<String> errors) {
    for (final entry in files.entries) {
      if (entry.key.startsWith('.agents/skills/')) {
        _validateSkillSyntax(entry.key, entry.value, errors);
      } else if (entry.key.startsWith('.codex/agents/')) {
        _validateAgentSyntax(entry.key, entry.value, errors);
      }
    }
  }

  void _validateSkillSyntax(String path, String content, List<String> errors) {
    final lines = const LineSplitter().convert(content);
    if (lines.isEmpty || lines.first != '---') {
      errors.add('Codex Skill 必须以 YAML frontmatter 开头：$path');
      return;
    }
    final end = lines.indexOf('---', 1);
    if (end < 0) {
      errors.add('Codex Skill 的 YAML frontmatter 未闭合：$path');
      return;
    }
    try {
      final metadata = loadYaml(lines.sublist(1, end).join('\n'));
      if (metadata is! YamlMap ||
          metadata.keys.toSet().difference(const {
            'name',
            'description',
          }).isNotEmpty ||
          metadata['name'] is! String ||
          metadata['description'] is! String) {
        errors.add('Codex Skill 只能声明非空 name 和 description：$path');
        return;
      }
      final name = metadata['name'] as String;
      final description = metadata['description'] as String;
      final pathName = path.split('/').elementAt(path.split('/').length - 2);
      if (name != pathName || description.trim().isEmpty) {
        errors.add('Codex Skill 的 name/description 无效：$path');
      }
    } on YamlException catch (error) {
      errors.add('Codex Skill 的 YAML 无效：$path：${error.message}');
    }
  }

  void _validateAgentSyntax(String path, String content, List<String> errors) {
    final lines = const LineSplitter().convert(content);
    if (lines.isEmpty || lines.first != '# $_generatedMarker') {
      errors.add('Codex Agent 缺少生成标记：$path');
      return;
    }
    final values = <String, String>{};
    try {
      for (final line in lines.skip(1).where((line) => line.isNotEmpty)) {
        final match = RegExp(r'^([a-z_]+) = (.+)$').firstMatch(line);
        if (match == null) {
          errors.add('Codex Agent 包含无效 TOML 字段：$path');
          return;
        }
        final value = jsonDecode(match.group(2)!);
        if (value is! String || values.containsKey(match.group(1))) {
          errors.add('Codex Agent 包含无效或重复 TOML 字段：$path');
          return;
        }
        values[match.group(1)!] = value;
      }
    } on FormatException catch (error) {
      errors.add('Codex Agent 的 TOML 字符串无效：$path：${error.message}');
      return;
    }
    if (values.keys.toSet().difference(const {
          'name',
          'description',
          'developer_instructions',
        }).isNotEmpty ||
        values.length != 3 ||
        values.values.any((value) => value.trim().isEmpty)) {
      errors.add(
        'Codex Agent 必须声明 name、description 和 developer_instructions：$path',
      );
      return;
    }
    final pathName = _basename(path).replaceFirst(RegExp(r'\.toml$'), '');
    if (values['name'] != pathName) {
      errors.add('Codex Agent 的 name 与路径不一致：$path');
    }
  }

  List<String> sync() {
    try {
      return _sync();
    } on FileSystemException catch (error) {
      return ['Codex 适配同步失败：${_fileSystemError(error)}'];
    }
  }

  List<String> _sync() {
    final result = _buildExpectedFiles();
    if (result.errors.isNotEmpty) {
      return result.errors;
    }

    final errors = <String>[];
    _validateExpectedSyntax(result.files, errors);
    _validateManagedLayout(result.files.keys, errors);
    if (errors.isNotEmpty) {
      return errors;
    }

    final generatedFiles = _generatedAdapterFiles(errors).toList();
    if (errors.isNotEmpty) {
      return errors;
    }
    for (final entry in result.files.entries) {
      final file = _file(entry.key);
      if (file.existsSync() && !_isGenerated(file.readAsStringSync())) {
        errors.add('Codex 适配路径存在同名非生成文件：${entry.key}');
      }
    }
    if (errors.isNotEmpty) {
      return errors;
    }

    final staleFiles = [
      for (final file in generatedFiles)
        if (!result.files.containsKey(_relative(file))) file,
    ];
    final transactionPaths = <String>{
      ...result.files.keys,
      ...staleFiles.map(_relative),
    }.toList()..sort();
    final originals = <String, List<int>?>{};
    for (final relative in transactionPaths) {
      final file = _file(relative);
      originals[relative] = file.existsSync() ? file.readAsBytesSync() : null;
    }

    final staging = Directory.fromUri(
      root.absolute.uri.resolve(
        '.codex-adapters-tmp-$pid-${DateTime.now().microsecondsSinceEpoch}/',
      ),
    );
    final createdDirectories = <Directory>[];
    try {
      staging.createSync();
      var index = 0;
      final stagedFiles = <String, File>{};
      for (final entry in result.files.entries) {
        final staged = File.fromUri(staging.uri.resolve('${index++}.tmp'));
        staged.writeAsStringSync(entry.value, flush: true);
        stagedFiles[entry.key] = staged;
      }

      for (final entry in result.files.entries) {
        final target = _file(entry.key);
        _createParentDirectories(target.parent, createdDirectories);
        final commitErrors = <String>[];
        _validateManagedPath(entry.key, commitErrors, expectedDirectory: false);
        if (commitErrors.isNotEmpty) {
          throw FileSystemException(commitErrors.join('；'), target.path);
        }
        stagedFiles[entry.key]!.renameSync(target.path);
      }

      for (final stale in staleFiles) {
        final stalePath = _relative(stale);
        final commitErrors = <String>[];
        _validateManagedPath(stalePath, commitErrors, expectedDirectory: false);
        if (commitErrors.isNotEmpty) {
          throw FileSystemException(commitErrors.join('；'), stale.path);
        }
        stale.deleteSync();
      }
    } on FileSystemException catch (error) {
      final rollbackErrors = _restoreOriginals(
        originals,
        createdDirectories: createdDirectories,
      );
      rollbackErrors.addAll(_cleanupTransactionArtifacts(staging));
      final rollbackSuffix = rollbackErrors.isEmpty
          ? ''
          : '；回滚异常：${rollbackErrors.join('；')}';
      return ['Codex 适配同步失败：${_fileSystemError(error)}$rollbackSuffix'];
    }

    final cleanupErrors = _cleanupTransactionArtifacts(staging);
    if (cleanupErrors.isNotEmpty) {
      return ['Codex 适配同步完成，但临时文件清理失败：${cleanupErrors.join('；')}'];
    }
    for (final file in staleFiles) {
      _deleteEmptyGeneratedParent(file.parent);
    }
    return check();
  }

  _ExpectedFilesResult _buildExpectedFiles() {
    final errors = <String>[];
    final files = <String, String>{'AGENTS.md': _agentsAdapter()};
    final skillNames = <String>{};

    for (final source in _readSkills(errors)) {
      skillNames.add(source.name);
      files['.agents/skills/${source.name}/SKILL.md'] = _skillAdapter(
        source,
        command: false,
      );
    }
    for (final source in _readCommands(errors)) {
      if (!skillNames.add(source.name)) {
        errors.add(
          'Claude Command 与 Skill 名称冲突，无法生成 Codex Skill：'
          '${source.name}',
        );
        continue;
      }
      files['.agents/skills/${source.name}/SKILL.md'] = _skillAdapter(
        source,
        command: true,
      );
    }
    for (final source in _readAgents(errors)) {
      files['.codex/agents/${source.name}.toml'] = _agentAdapter(source);
    }

    return _ExpectedFilesResult(files: files, errors: errors);
  }

  List<_ClaudeAsset> _readSkills(List<String> errors) {
    const base = '.claude/skills';
    final directory = _directory(base);
    if (!directory.existsSync()) {
      errors.add('缺少 Claude Skill 目录：$base');
      return const [];
    }
    final files =
        directory
            .listSync(followLinks: false)
            .whereType<Directory>()
            .map((directory) => File.fromUri(directory.uri.resolve('SKILL.md')))
            .where((file) => file.existsSync())
            .toList()
          ..sort((left, right) => left.path.compareTo(right.path));
    return [
      for (final file in files)
        if (_readAsset(file, errors, requireName: true, nameFromParent: true)
            case final asset?)
          asset,
    ];
  }

  List<_ClaudeAsset> _readCommands(List<String> errors) => _readFlatAssets(
    '.claude/commands',
    errors,
    requireName: false,
    nameFromParent: false,
    readArgumentHint: true,
  );

  List<_ClaudeAsset> _readAgents(List<String> errors) => _readFlatAssets(
    '.claude/agents',
    errors,
    requireName: true,
    nameFromParent: false,
    readArgumentHint: false,
  );

  List<_ClaudeAsset> _readFlatAssets(
    String relativeDirectory,
    List<String> errors, {
    required bool requireName,
    required bool nameFromParent,
    required bool readArgumentHint,
  }) {
    final directory = _directory(relativeDirectory);
    if (!directory.existsSync()) {
      errors.add('缺少 Claude 资产目录：$relativeDirectory');
      return const [];
    }
    final files =
        directory
            .listSync(followLinks: false)
            .whereType<File>()
            .where((file) => file.path.endsWith('.md'))
            .toList()
          ..sort((left, right) => left.path.compareTo(right.path));
    return [
      for (final file in files)
        if (_readAsset(
              file,
              errors,
              requireName: requireName,
              nameFromParent: nameFromParent,
              readArgumentHint: readArgumentHint,
            )
            case final asset?)
          asset,
    ];
  }

  _ClaudeAsset? _readAsset(
    File file,
    List<String> errors, {
    required bool requireName,
    required bool nameFromParent,
    bool readArgumentHint = false,
  }) {
    final relative = _relative(file);
    final lines = file.readAsLinesSync();
    if (lines.isEmpty || lines.first.trim() != '---') {
      errors.add('$relative 缺少 YAML frontmatter');
      return null;
    }
    final end = lines.indexWhere((line) => line.trim() == '---', 1);
    if (end < 0) {
      errors.add('$relative 的 YAML frontmatter 未闭合');
      return null;
    }

    final YamlMap metadata;
    try {
      final parsed = loadYaml(lines.sublist(1, end).join('\n'));
      if (parsed is! YamlMap) {
        errors.add('$relative 的 frontmatter 必须是 Map');
        return null;
      }
      metadata = parsed;
    } on YamlException catch (error) {
      errors.add('$relative 的 YAML 无效：${error.message}');
      return null;
    }

    final pathName = nameFromParent
        ? _basename(file.parent.path)
        : _basename(file.path).replaceFirst(RegExp(r'\.md$'), '');
    final declaredName = metadata['name'];
    final name = requireName ? declaredName : pathName;
    final description = metadata['description'];
    if (name is! String || name.trim().isEmpty) {
      errors.add('$relative 缺少非空 name');
      return null;
    }
    if (name != pathName) {
      errors.add('$relative 的 name=$name 与路径 $pathName 不一致');
      return null;
    }
    if (!RegExp(r'^[a-z][a-z0-9-]*$').hasMatch(name)) {
      errors.add('$relative 的名称不符合 kebab-case：$name');
      return null;
    }
    if (description is! String || description.trim().isEmpty) {
      errors.add('$relative 缺少非空 description');
      return null;
    }
    final rawArgumentHint = metadata['argument-hint'];
    if (readArgumentHint &&
        rawArgumentHint != null &&
        rawArgumentHint is! String) {
      errors.add('$relative 的 argument-hint 必须是字符串');
      return null;
    }
    return _ClaudeAsset(
      name: name,
      description: description,
      sourcePath: relative,
      argumentHint: readArgumentHint ? rawArgumentHint as String? : null,
    );
  }

  Iterable<File> _generatedAdapterFiles(List<String> errors) sync* {
    final skills = _directory('.agents/skills');
    if (skills.existsSync()) {
      for (final entity in skills.listSync(
        recursive: true,
        followLinks: false,
      )) {
        if (entity is Link) {
          errors.add('Codex 适配目录不允许符号链接：${_relativeEntity(entity)}');
          continue;
        }
        if (entity is! File || _basename(entity.path) != 'SKILL.md') {
          continue;
        }
        if (_isGenerated(entity.readAsStringSync())) {
          yield entity;
        }
      }
    }
    final agents = _directory('.codex/agents');
    if (agents.existsSync()) {
      for (final entity in agents.listSync(followLinks: false)) {
        if (entity is Link) {
          errors.add('Codex 适配目录不允许符号链接：${_relativeEntity(entity)}');
          continue;
        }
        if (entity is File &&
            entity.path.endsWith('.toml') &&
            _isGenerated(entity.readAsStringSync())) {
          yield entity;
        }
      }
    }
  }

  void _deleteEmptyGeneratedParent(Directory directory) {
    final relative = directory.path
        .substring(root.absolute.path.length)
        .replaceAll('\\', '/')
        .replaceFirst(RegExp(r'^/'), '');
    if (!relative.startsWith('.agents/skills/') ||
        !directory.existsSync() ||
        directory.listSync().isNotEmpty) {
      return;
    }
    directory.deleteSync();
  }

  void _validateManagedLayout(
    Iterable<String> expectedPaths,
    List<String> errors,
  ) {
    if (!root.existsSync()) {
      errors.add('Codex 适配仓库根目录不存在：${root.path}');
      return;
    }
    _validateManagedPath('.agents/skills', errors, expectedDirectory: true);
    _validateManagedPath('.codex/agents', errors, expectedDirectory: true);
    for (final path in expectedPaths) {
      _validateManagedPath(path, errors, expectedDirectory: false);
    }
  }

  void _validateManagedPath(
    String relativePath,
    List<String> errors, {
    required bool expectedDirectory,
  }) {
    final components = relativePath.split('/');
    if (relativePath.isEmpty ||
        relativePath.startsWith('/') ||
        components.any((component) => component.isEmpty || component == '..')) {
      errors.add('Codex 适配路径不是安全的仓库相对路径：$relativePath');
      return;
    }

    final canonicalRoot = root.resolveSymbolicLinksSync();
    var current = root.absolute.path;
    for (var index = 0; index < components.length; index++) {
      current = _joinPath(current, components[index]);
      final type = FileSystemEntity.typeSync(current, followLinks: false);
      if (type == FileSystemEntityType.notFound) {
        continue;
      }
      if (type == FileSystemEntityType.link) {
        errors.add('Codex 适配路径不允许符号链接：$relativePath');
        return;
      }

      final isLast = index == components.length - 1;
      if (!isLast && type != FileSystemEntityType.directory) {
        errors.add('Codex 适配父路径必须是目录：$relativePath');
        return;
      }
      if (isLast &&
          ((expectedDirectory && type != FileSystemEntityType.directory) ||
              (!expectedDirectory && type != FileSystemEntityType.file))) {
        final expectedKind = expectedDirectory ? '目录' : '文件';
        errors.add('Codex 适配路径必须是$expectedKind：$relativePath');
        return;
      }

      final resolved = type == FileSystemEntityType.directory
          ? Directory(current).resolveSymbolicLinksSync()
          : File(current).resolveSymbolicLinksSync();
      if (!_isWithinRoot(resolved, canonicalRoot)) {
        errors.add('Codex 适配路径解析到仓库外：$relativePath');
        return;
      }
    }
  }

  bool _isWithinRoot(String candidate, String canonicalRoot) {
    final normalizedCandidate = Platform.isWindows
        ? candidate.toLowerCase()
        : candidate;
    final normalizedRoot = Platform.isWindows
        ? canonicalRoot.toLowerCase()
        : canonicalRoot;
    return normalizedCandidate == normalizedRoot ||
        normalizedCandidate.startsWith(
          '$normalizedRoot${Platform.pathSeparator}',
        );
  }

  void _createParentDirectories(
    Directory directory,
    List<Directory> createdDirectories,
  ) {
    if (directory.existsSync()) {
      return;
    }
    if (directory.absolute.path == root.absolute.path) {
      return;
    }
    _createParentDirectories(directory.parent, createdDirectories);
    directory.createSync();
    createdDirectories.add(directory);
  }

  List<String> _restoreOriginals(
    Map<String, List<int>?> originals, {
    required List<Directory> createdDirectories,
  }) {
    final errors = <String>[];
    for (final entry in originals.entries) {
      final target = _file(entry.key);
      try {
        final type = FileSystemEntity.typeSync(target.path, followLinks: false);
        if (type == FileSystemEntityType.link ||
            type == FileSystemEntityType.directory) {
          errors.add('${entry.key} 的节点类型在同步期间发生变化');
          continue;
        }
        if (entry.value == null) {
          if (type == FileSystemEntityType.file) {
            target.deleteSync();
          }
          continue;
        }
        target.parent.createSync(recursive: true);
        target.writeAsBytesSync(entry.value!, flush: true);
      } on FileSystemException catch (error) {
        errors.add('${entry.key}：${_fileSystemError(error)}');
      }
    }
    for (final directory in createdDirectories.reversed) {
      try {
        if (directory.existsSync() && directory.listSync().isEmpty) {
          directory.deleteSync();
        }
      } on FileSystemException catch (error) {
        errors.add(
          '${_relativeDirectory(directory)}：${_fileSystemError(error)}',
        );
      }
    }
    return errors;
  }

  List<String> _cleanupTransactionArtifacts(Directory staging) {
    final errors = <String>[];
    try {
      if (staging.existsSync()) {
        staging.deleteSync(recursive: true);
      }
    } on FileSystemException catch (error) {
      errors.add(_fileSystemError(error));
    }
    return errors;
  }

  String _normalizeLineEndings(String content) =>
      content.replaceAll('\r\n', '\n').replaceAll('\r', '\n');

  bool _isGenerated(String content) => _normalizeLineEndings(
    content,
  ).split('\n').take(3).any((line) => line.contains(_generatedMarker));

  String _agentsAdapter() => '''<!-- $_generatedMarker -->
# Codex 项目入口

本仓库以 [`CLAUDE.md`](./CLAUDE.md) 为唯一权威项目契约。

开始任何任务前，必须完整读取 `CLAUDE.md`，并按其中要求加载当前任务相关的
`.claude/commands/`、`.claude/agents/`、`.claude/skills/` 和
`.claude/memories/` 文件。

本文件只负责 Codex 入口适配，不重复项目规则。发生冲突时以 `CLAUDE.md` 为准。
''';

  String _skillAdapter(_ClaudeAsset source, {required bool command}) {
    final kind = command ? 'Command 工作流' : 'Skill';
    final argumentInstruction = command ? _commandArguments(source) : '';
    return '''---
# $_generatedMarker
name: ${source.name}
description: ${jsonEncode(source.description)}
---

# ${source.name}

这是 Claude $kind 的 Codex 原生发现入口。执行前必须完整读取并遵守
[`$kind 事实源`](../../../${source.sourcePath})。$argumentInstruction

不要在本文件复制或修改工作流正文。
''';
  }

  String _commandArguments(_ClaudeAsset source) {
    final hint = source.argumentHint?.trim();
    final hintInstruction = hint == null || hint.isEmpty
        ? '- 参数提示：源 Command 未声明 `argument-hint`。'
        : '- 参数提示：`${hint.replaceAll('`', r'\`')}`。';
    return '''

参数映射：

$hintInstruction
- 显式调用 `\$${source.name} ...` 时，移除只用于选择 Skill 的
  `\$${source.name}` token，其余用户输入作为 `\$ARGUMENTS`。
- 由语义匹配触发时，完整的当前用户任务输入作为 `\$ARGUMENTS`。
- 必需参数缺失时，遵守源 Command 的停止条件，不猜测输入。''';
  }

  String _agentAdapter(_ClaudeAsset source) {
    final instructions =
        '开始工作前，完整读取并严格遵守 `${source.sourcePath}`。'
        '该 Markdown 是角色行为的唯一事实源；本 TOML 只负责 Codex 原生发现。';
    return '''# $_generatedMarker
name = ${jsonEncode(source.name)}
description = ${jsonEncode(source.description)}
developer_instructions = ${jsonEncode(instructions)}
''';
  }

  File _file(String relativePath) =>
      File.fromUri(root.absolute.uri.resolve(relativePath));

  Directory _directory(String relativePath) => Directory.fromUri(
    root.absolute.uri.resolve(
      relativePath.endsWith('/') ? relativePath : '$relativePath/',
    ),
  );

  String _relative(File file) => file.path
      .substring(root.absolute.path.length)
      .replaceAll('\\', '/')
      .replaceFirst(RegExp(r'^/'), '');

  String _relativeEntity(FileSystemEntity entity) => entity.path
      .substring(root.absolute.path.length)
      .replaceAll('\\', '/')
      .replaceFirst(RegExp(r'^/'), '');

  String _relativeDirectory(Directory directory) => directory.path
      .substring(root.absolute.path.length)
      .replaceAll('\\', '/')
      .replaceFirst(RegExp(r'^/'), '');

  String _joinPath(String parent, String child) =>
      parent.endsWith(Platform.pathSeparator)
      ? '$parent$child'
      : '$parent${Platform.pathSeparator}$child';

  String _fileSystemError(FileSystemException error) {
    final path = error.path == null ? '' : '（${_safeErrorPath(error.path!)}）';
    return '${_sanitizeErrorMessage(error.message)}$path';
  }

  String _sanitizeErrorMessage(String message) {
    return message.replaceAll(root.absolute.path, '<repo>');
  }

  String _safeErrorPath(String path) {
    final absolutePath = File(path).absolute.path;
    final absoluteRoot = root.absolute.path;
    if (!_isWithinRoot(absolutePath, absoluteRoot)) {
      return '<outside-path>';
    }
    final relative = absolutePath
        .substring(absoluteRoot.length)
        .replaceAll('\\', '/')
        .replaceFirst(RegExp(r'^/'), '');
    return relative.isEmpty ? '<repo>' : '<repo>/$relative';
  }

  String _basename(String path) => path.replaceAll('\\', '/').split('/').last;
}

class _ClaudeAsset {
  const _ClaudeAsset({
    required this.name,
    required this.description,
    required this.sourcePath,
    this.argumentHint,
  });

  final String name;
  final String description;
  final String sourcePath;
  final String? argumentHint;
}

class _ExpectedFilesResult {
  const _ExpectedFilesResult({required this.files, required this.errors});

  final Map<String, String> files;
  final List<String> errors;
}
