import 'dart:convert';
import 'dart:io';

import 'package:yaml/yaml.dart';

const _generatedMarker =
    'Generated by app/tool/sync_codex_adapters.dart. DO NOT EDIT.';

class CodexAdapterManager {
  CodexAdapterManager(this.root);

  final Directory root;

  List<String> check() {
    final result = _buildExpectedFiles();
    if (result.errors.isNotEmpty) {
      return result.errors;
    }

    final errors = <String>[];
    _validateExpectedSyntax(result.files, errors);
    for (final entry in result.files.entries) {
      final file = _file(entry.key);
      if (!file.existsSync()) {
        errors.add('缺少 Codex 适配：${entry.key}');
        continue;
      }
      final actual = file.readAsStringSync();
      if (actual == entry.value) {
        continue;
      }
      if (!_isGenerated(actual)) {
        errors.add('Codex 适配路径存在同名非生成文件：${entry.key}');
      } else {
        errors.add('Codex 适配内容已漂移：${entry.key}');
      }
    }

    for (final file in _generatedAdapterFiles()) {
      final relative = _relative(file);
      if (!result.files.containsKey(relative)) {
        errors.add('存在过期 Codex 适配：$relative');
      }
    }
    return errors;
  }

  void _validateExpectedSyntax(Map<String, String> files, List<String> errors) {
    for (final entry in files.entries) {
      if (entry.key.startsWith('.agents/skills/')) {
        _validateSkillSyntax(entry.key, entry.value, errors);
      } else if (entry.key.startsWith('.codex/agents/')) {
        _validateAgentSyntax(entry.key, entry.value, errors);
      }
    }
  }

  void _validateSkillSyntax(String path, String content, List<String> errors) {
    final lines = const LineSplitter().convert(content);
    if (lines.isEmpty || lines.first != '---') {
      errors.add('Codex Skill 必须以 YAML frontmatter 开头：$path');
      return;
    }
    final end = lines.indexOf('---', 1);
    if (end < 0) {
      errors.add('Codex Skill 的 YAML frontmatter 未闭合：$path');
      return;
    }
    try {
      final metadata = loadYaml(lines.sublist(1, end).join('\n'));
      if (metadata is! YamlMap ||
          metadata.keys.toSet().difference(const {
            'name',
            'description',
          }).isNotEmpty ||
          metadata['name'] is! String ||
          metadata['description'] is! String) {
        errors.add('Codex Skill 只能声明非空 name 和 description：$path');
        return;
      }
      final name = metadata['name'] as String;
      final description = metadata['description'] as String;
      final pathName = path.split('/').elementAt(path.split('/').length - 2);
      if (name != pathName || description.trim().isEmpty) {
        errors.add('Codex Skill 的 name/description 无效：$path');
      }
    } on YamlException catch (error) {
      errors.add('Codex Skill 的 YAML 无效：$path：${error.message}');
    }
  }

  void _validateAgentSyntax(String path, String content, List<String> errors) {
    final lines = const LineSplitter().convert(content);
    if (lines.isEmpty || lines.first != '# $_generatedMarker') {
      errors.add('Codex Agent 缺少生成标记：$path');
      return;
    }
    final values = <String, String>{};
    try {
      for (final line in lines.skip(1).where((line) => line.isNotEmpty)) {
        final match = RegExp(r'^([a-z_]+) = (.+)$').firstMatch(line);
        if (match == null) {
          errors.add('Codex Agent 包含无效 TOML 字段：$path');
          return;
        }
        final value = jsonDecode(match.group(2)!);
        if (value is! String || values.containsKey(match.group(1))) {
          errors.add('Codex Agent 包含无效或重复 TOML 字段：$path');
          return;
        }
        values[match.group(1)!] = value;
      }
    } on FormatException catch (error) {
      errors.add('Codex Agent 的 TOML 字符串无效：$path：${error.message}');
      return;
    }
    if (values.keys.toSet().difference(const {
          'name',
          'description',
          'developer_instructions',
        }).isNotEmpty ||
        values.length != 3 ||
        values.values.any((value) => value.trim().isEmpty)) {
      errors.add(
        'Codex Agent 必须声明 name、description 和 developer_instructions：$path',
      );
      return;
    }
    final pathName = _basename(path).replaceFirst(RegExp(r'\.toml$'), '');
    if (values['name'] != pathName) {
      errors.add('Codex Agent 的 name 与路径不一致：$path');
    }
  }

  List<String> sync() {
    final result = _buildExpectedFiles();
    if (result.errors.isNotEmpty) {
      return result.errors;
    }

    final errors = <String>[];
    for (final entry in result.files.entries) {
      final file = _file(entry.key);
      if (file.existsSync() && !_isGenerated(file.readAsStringSync())) {
        errors.add('Codex 适配路径存在同名非生成文件：${entry.key}');
      }
    }
    if (errors.isNotEmpty) {
      return errors;
    }

    for (final file in _generatedAdapterFiles()) {
      final relative = _relative(file);
      if (result.files.containsKey(relative)) {
        continue;
      }
      file.deleteSync();
      _deleteEmptyGeneratedParent(file.parent);
    }

    for (final entry in result.files.entries) {
      final file = _file(entry.key);
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(entry.value);
    }
    return check();
  }

  _ExpectedFilesResult _buildExpectedFiles() {
    final errors = <String>[];
    final files = <String, String>{'AGENTS.md': _agentsAdapter()};
    final skillNames = <String>{};

    for (final source in _readSkills(errors)) {
      skillNames.add(source.name);
      files['.agents/skills/${source.name}/SKILL.md'] = _skillAdapter(
        source,
        command: false,
      );
    }
    for (final source in _readCommands(errors)) {
      if (!skillNames.add(source.name)) {
        errors.add(
          'Claude Command 与 Skill 名称冲突，无法生成 Codex Skill：'
          '${source.name}',
        );
        continue;
      }
      files['.agents/skills/${source.name}/SKILL.md'] = _skillAdapter(
        source,
        command: true,
      );
    }
    for (final source in _readAgents(errors)) {
      files['.codex/agents/${source.name}.toml'] = _agentAdapter(source);
    }

    return _ExpectedFilesResult(files: files, errors: errors);
  }

  List<_ClaudeAsset> _readSkills(List<String> errors) {
    const base = '.claude/skills';
    final directory = _directory(base);
    if (!directory.existsSync()) {
      errors.add('缺少 Claude Skill 目录：$base');
      return const [];
    }
    final files =
        directory
            .listSync(followLinks: false)
            .whereType<Directory>()
            .map((directory) => File.fromUri(directory.uri.resolve('SKILL.md')))
            .where((file) => file.existsSync())
            .toList()
          ..sort((left, right) => left.path.compareTo(right.path));
    return [
      for (final file in files)
        if (_readAsset(file, errors, requireName: true, nameFromParent: true)
            case final asset?)
          asset,
    ];
  }

  List<_ClaudeAsset> _readCommands(List<String> errors) => _readFlatAssets(
    '.claude/commands',
    errors,
    requireName: false,
    nameFromParent: false,
  );

  List<_ClaudeAsset> _readAgents(List<String> errors) => _readFlatAssets(
    '.claude/agents',
    errors,
    requireName: true,
    nameFromParent: false,
  );

  List<_ClaudeAsset> _readFlatAssets(
    String relativeDirectory,
    List<String> errors, {
    required bool requireName,
    required bool nameFromParent,
  }) {
    final directory = _directory(relativeDirectory);
    if (!directory.existsSync()) {
      errors.add('缺少 Claude 资产目录：$relativeDirectory');
      return const [];
    }
    final files =
        directory
            .listSync(followLinks: false)
            .whereType<File>()
            .where((file) => file.path.endsWith('.md'))
            .toList()
          ..sort((left, right) => left.path.compareTo(right.path));
    return [
      for (final file in files)
        if (_readAsset(
              file,
              errors,
              requireName: requireName,
              nameFromParent: nameFromParent,
            )
            case final asset?)
          asset,
    ];
  }

  _ClaudeAsset? _readAsset(
    File file,
    List<String> errors, {
    required bool requireName,
    required bool nameFromParent,
  }) {
    final relative = _relative(file);
    final lines = file.readAsLinesSync();
    if (lines.isEmpty || lines.first.trim() != '---') {
      errors.add('$relative 缺少 YAML frontmatter');
      return null;
    }
    final end = lines.indexWhere((line) => line.trim() == '---', 1);
    if (end < 0) {
      errors.add('$relative 的 YAML frontmatter 未闭合');
      return null;
    }

    final YamlMap metadata;
    try {
      final parsed = loadYaml(lines.sublist(1, end).join('\n'));
      if (parsed is! YamlMap) {
        errors.add('$relative 的 frontmatter 必须是 Map');
        return null;
      }
      metadata = parsed;
    } on YamlException catch (error) {
      errors.add('$relative 的 YAML 无效：${error.message}');
      return null;
    }

    final pathName = nameFromParent
        ? _basename(file.parent.path)
        : _basename(file.path).replaceFirst(RegExp(r'\.md$'), '');
    final declaredName = metadata['name'];
    final name = requireName ? declaredName : pathName;
    final description = metadata['description'];
    if (name is! String || name.trim().isEmpty) {
      errors.add('$relative 缺少非空 name');
      return null;
    }
    if (name != pathName) {
      errors.add('$relative 的 name=$name 与路径 $pathName 不一致');
      return null;
    }
    if (!RegExp(r'^[a-z][a-z0-9-]*$').hasMatch(name)) {
      errors.add('$relative 的名称不符合 kebab-case：$name');
      return null;
    }
    if (description is! String || description.trim().isEmpty) {
      errors.add('$relative 缺少非空 description');
      return null;
    }
    return _ClaudeAsset(
      name: name,
      description: description,
      sourcePath: relative,
    );
  }

  Iterable<File> _generatedAdapterFiles() sync* {
    final skills = _directory('.agents/skills');
    if (skills.existsSync()) {
      for (final entity in skills.listSync(
        recursive: true,
        followLinks: false,
      )) {
        if (entity is! File || _basename(entity.path) != 'SKILL.md') {
          continue;
        }
        if (_isGenerated(entity.readAsStringSync())) {
          yield entity;
        }
      }
    }
    final agents = _directory('.codex/agents');
    if (agents.existsSync()) {
      for (final entity in agents.listSync(followLinks: false)) {
        if (entity is File &&
            entity.path.endsWith('.toml') &&
            _isGenerated(entity.readAsStringSync())) {
          yield entity;
        }
      }
    }
  }

  void _deleteEmptyGeneratedParent(Directory directory) {
    final relative = directory.path
        .substring(root.path.length)
        .replaceAll('\\', '/')
        .replaceFirst(RegExp(r'^/'), '');
    if (!relative.startsWith('.agents/skills/') ||
        !directory.existsSync() ||
        directory.listSync().isNotEmpty) {
      return;
    }
    directory.deleteSync();
  }

  bool _isGenerated(String content) => content
      .split('\n')
      .take(3)
      .any((line) => line.contains(_generatedMarker));

  String _agentsAdapter() => '''<!-- $_generatedMarker -->
# Codex 项目入口

本仓库以 [`CLAUDE.md`](./CLAUDE.md) 为唯一权威项目契约。

开始任何任务前，必须完整读取 `CLAUDE.md`，并按其中要求加载当前任务相关的
`.claude/commands/`、`.claude/agents/`、`.claude/skills/` 和
`.claude/memories/` 文件。

本文件只负责 Codex 入口适配，不重复项目规则。发生冲突时以 `CLAUDE.md` 为准。
''';

  String _skillAdapter(_ClaudeAsset source, {required bool command}) {
    final kind = command ? 'Command 工作流' : 'Skill';
    final argumentInstruction = command
        ? '\n将当前用户请求视为该 Command 的 `\$ARGUMENTS`。'
        : '';
    return '''---
# $_generatedMarker
name: ${source.name}
description: ${jsonEncode(source.description)}
---

# ${source.name}

这是 Claude $kind 的 Codex 原生发现入口。执行前必须完整读取并遵守
[`$kind 事实源`](../../../${source.sourcePath})。$argumentInstruction

不要在本文件复制或修改工作流正文。
''';
  }

  String _agentAdapter(_ClaudeAsset source) {
    final instructions =
        '开始工作前，完整读取并严格遵守 `${source.sourcePath}`。'
        '该 Markdown 是角色行为的唯一事实源；本 TOML 只负责 Codex 原生发现。';
    return '''# $_generatedMarker
name = ${jsonEncode(source.name)}
description = ${jsonEncode(source.description)}
developer_instructions = ${jsonEncode(instructions)}
''';
  }

  File _file(String relativePath) =>
      File.fromUri(root.uri.resolve(relativePath));

  Directory _directory(String relativePath) => Directory.fromUri(
    root.uri.resolve(
      relativePath.endsWith('/') ? relativePath : '$relativePath/',
    ),
  );

  String _relative(File file) => file.path
      .substring(root.path.length)
      .replaceAll('\\', '/')
      .replaceFirst(RegExp(r'^/'), '');

  String _basename(String path) => path.replaceAll('\\', '/').split('/').last;
}

class _ClaudeAsset {
  const _ClaudeAsset({
    required this.name,
    required this.description,
    required this.sourcePath,
  });

  final String name;
  final String description;
  final String sourcePath;
}

class _ExpectedFilesResult {
  const _ExpectedFilesResult({required this.files, required this.errors});

  final Map<String, String> files;
  final List<String> errors;
}
